---
  .gitlab-ci.yml:
    delete: true
  appveyor.yml:
    delete: true
  Gemfile:
    optional:
      ':development':
        - gem: 'github_changelog_generator'
          version: '~> 1.15.0'
        - gem: 'puppet-lint-top_scope_facts-check'
          version: '~> 1.0.1'
        - gem: 'puppet-lint-legacy_facts-check'
          version: '~> 1.0.3'
  Rakefile:
    changelog_user: 'genebean'
    changelog_project: 'genebean-zabbixagent'
    changelog_version_tag_pattern: '%s'
    requires:
      - 'puppet-strings/tasks'
  spec/spec_helper.rb:
    mock_with: ':rspec'
    coverage_report: true
